######################## default configuration ####################
baseURL = "https://grad-masterov.ru"
languageCode = "ru"
title = "Град Мастеров | Фестивали и Ярмарки на КМВ и online"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""
enableEmoji = true
############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Товары"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Блог"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "ЧаВо"
  URL = "faq"
  weight = 3

  [[menu.main]]
  name = "Контакты"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Товары"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Блог"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "ЧаВо"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Правила и соглашения"
  URL = "terms-conditions"
  weight = 4

  [[menu.footer]]
  name = "Контакты"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "🏠"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places&region=RU&language=ru"
mapLatitude = "43.935840853644144"
mapLongitude = "42.721565215650585"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "89187887119"
email = "shop@grad-masterov.ru"
location = "КМВ, Ставропольский край"
# copyright
copyright = "| Copyright &copy; 2021 [goshva](mailto:sha.egor@gmail.com) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "ZDhmNDZiZWYtYmE0Yi00ZGE3LTk2MTYtZTZlY2NhOGRjMDFmNjM3NTAwOTQ5ODUwMDc3NzU4"
#currencySymbol = "$"
currencySymbol = "₽"
addToCard = "Добавить в корзину"
ask = "Задать свой вопрос"
sendnow = "Отправить"
youname ="Ваше имя"
youmsg = "Наберите сообщение"

address= "Россия, Ставропольский край, Кисловодск, улица Чайковского, 26А"
  # Preloader
  [params.preloader]
  enable = true
  preloader = "/images/logo.png" # use .png , .svg or .gif format
  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/grad_masterov/"

  [[params.social]]
  icon = "ti-pinterest"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
